### ISSUE TITLE
Fix menu item highlighting

### ISSUE THREAD

**Issue by webbertakken** [game-ci/documentation#130]
Menu should be highlighting the page that's currently open.

I probably made a mismatch in keys in `MenuSidebar`.

**Comment by julhad** [comment]
Does this issue address the highlighting for the old (v1) docs (e.g. https://game.ci/docs/github/v1/builder)? Because opening the current docs (e.g. https://game.ci/docs/gitlab/example-project) highlights the correct menu on the left for me (Safari 15.0).

**Comment by webbertakken** [comment]
If I open https://game.ci/docs/gitlab/deployment/android#bundle-version-code it's not highlighting the menu item correctly.
