### ISSUE TITLE
Make the GameCI logo dark theme compatible

### ISSUE THREAD

**Issue by GabLeRoux** [game-ci/documentation#153]
As discussed here: https://github.com/game-ci/documentation/pull/151#discussion_r624682843

GameCI Logo in header menu is a SVG and when using dark theme, we should switch the dark color to a bright color.

![image](https://user-images.githubusercontent.com/1264761/116820803-d3888f00-ab44-11eb-82e2-01f6ab6f3243.png)

It should be possible to achieve this by passing `color` to the logo and using that as a fill in the logo.
A workaround would be to load a different svg when dark theme is active.

**Comment by webbertakken** [comment]
Solved by #259
