### ISSUE TITLE
Typo in GitHub Getting started

### ISSUE THREAD

**Issue by TomiukQT** [game-ci/documentation#179]
I think there is typo on https://unity-ci.com/docs/github/getting-started in first paragraph. There should probably be GitHub Actions instead of Unity Actions

**Comment by GabLeRoux** [comment]
Good point, might be confusing a bit, but Github Actions and Unity Actions aren't the same. Unity-Action is the project that combines all of the related github-actions related to building and testing unity projects:

https://github.com/game-ci/unity-actions

It could be a bit more clear tho.

**Comment by TomiukQT** [comment]
Yeah. It really is more clear. Thanks

**Comment by webbertakken** [comment]
Thank you for your feedback!
