### ISSUE TITLE
Dark theme switch

### ISSUE THREAD

**Issue by webbertakken** [game-ci/documentation#18]
Currently the site hurts your eyes at night. We should add a dark mode switch with the options `on`, `off` and `same as operating system`.

The settings should be saved in a cookie (not localstorage) for potential server side rendering.

We'll need to find the best way to switch between Light and Dark themes and create an initial implementation.

**Comment by webbertakken** [comment]
Right now the best approach probably is this https://medium.com/@mzohaib.qc/ant-design-dynamic-runtime-theme-1f9a1a030ba0

Ideally we would use the approach that is proposed here (pending): https://github.com/ant-design/ant-design/issues/23371

**Comment by uchar** [comment]
@webbertakken I did this using redux in the [past](https://github.com/uchar/Q2A.js/blob/master/front_end/src/pages/_app.js), I can work on it if one else is doing it?

**Comment by webbertakken** [comment]
We are currently evaluation whether to stay with css or to go with the less variant instead.

The theme provider would indeed be a nice solution if we get it to work in a proper way. 

We should be able to do it without Redux thought.
Feel free to send your proposal for sure!

**Comment by webbertakken** [comment]
Fixed by #259
