### ISSUE TITLE
Version statues are not sorted correctly

### ISSUE THREAD

**Issue by uchar** [game-ci/documentation#182]
**Bug description**

In this [page](https://game.ci/docs/docker/versions) versions not sorted correctly : 

![image](https://user-images.githubusercontent.com/5172296/120762817-dc95c300-c52b-11eb-8c39-b75fff6497ae.png)

**Comment by Waryserpant122** [comment]
Hi , I have tried by writing a custom sort function to sort them in order in or #207. Please take a look and give feedback/comments on the same

**Comment by webbertakken** [comment]
Closed by https://github.com/game-ci/documentation/pull/207
