### ISSUE TITLE
Add copy button to code snippets

### ISSUE THREAD

**Issue by davidmfinol** [game-ci/documentation#204]
**Context**

Users are likely to copy-paste code snippets directly from the documentation website, and doing this copy-paste could be a better user experience.

**Suggested solution**

A copy button similar to what was added to GitHub: https://github.community/t/feature-request-code-copy-button-on-markdown-code-snippets/711

**Considered alternatives**

Users could continue with the current setup, but this would make for a nicer user experience.

**Comment by Waryserpant122** [comment]
Can I take up this issue?

**Comment by webbertakken** [comment]
Sure, please! go ahead.

**Comment by Waryserpant122** [comment]
Added a basic Pull Request with the first iteration #206
