### ISSUE TITLE
Markdown headings should have id's and act as anchors

### ISSUE THREAD

**Issue by webbertakken** [game-ci/documentation#26]
As a developer who'd like to share a specific portion of the readme with another developer, I'd like to be able to click any of the markdown headings (or an icon next to it) to acquire the URL to that section, so that I can link that information more accurately.

Example from [here](https://github.com/webbertakken/unity-builder/blob/master/README.md):

![image](https://user-images.githubusercontent.com/20756439/87256474-4ed46380-c493-11ea-8970-604f5b1a0745.png)

**Comment by juanmaotegui** [comment]
Can I work on it?
Which files are you referring to?

**Comment by webbertakken** [comment]
@juanmaotegui Yes feel free to assign the issue to yourself if you like to take it.

The markdown files can be found in [docs/github](https://github.com/Unity-CI/Website/tree/master/docs/github). These files are parsed to react components in [components/markdown](https://github.com/Unity-CI/Website/tree/master/components/markdown). The implementation that you see there uses [react-markdown](https://github.com/rexxars/react-markdown). React-markdown uses `renderers` which are documented [here](https://github.com/rexxars/react-markdown#node-types) and configured in [markdown-to-react-mapping.js](https://github.com/Unity-CI/Website/blob/master/components/markdown/markdown-to-react-mapping.js).

Feel free to ask if you need any more information.

**Comment by webbertakken** [comment]
This was fixed in #84
