### ISSUE TITLE
Enable proseWrap in Prettier

### ISSUE THREAD

**Issue by webbertakken** [game-ci/documentation#270]
![image](https://user-images.githubusercontent.com/20756439/169101321-89168bae-5e7c-4b18-b019-44ee8322cc31.png)

**Comment by webbertakken** [comment]
This should be merged at a moment where there are no PRs with large changes to documentation, to not disrupt peoples flows.

**Comment by davidmfinol** [comment]
@webbertakken I believe this is done now, right?

**Comment by webbertakken** [comment]
Fixed by #291
