### ISSUE TITLE
`UNITY_EDITOR` is not defined during build

### ISSUE THREAD

**Issue by florius0** [game-ci/documentation#295]
**Bug description**

`UNITY_EDITOR` seems not to be defined in compile-time.
I use a certain library in project on Unity 2021.3.3f1. On my machine (macOS) it compiles.
In CI (GitHub Actions) it does not:

The error:
```
Library/PackageCache/com.zappar.uar@84739170e2/Editor/ImageTrain/ZImageTrainer.cs(123,15):errorCS0426:Thetypename'FileData'does
not exist in the type
"Z
```

**How to reproduce**

Add [this library](https://github.com/Ninsar/universal-ar-unity.git) to a project and try building it.

- **Expected behavior**

The project should be built like when doing it on a local machin

**Additional details**

[https://github.com/Ninsar/goldn-apotheka](Project which I'm trying to build)

**Comment by davidmfinol** [comment]
Closing as not a documentation issue. Feel free to re-open under https://github.com/game-ci/unity-builder
