### ISSUE TITLE
Docker build for iOS target sometime freeze on UnityShaderCompilation

### ISSUE THREAD

**Issue by arczewski** [game-ci/documentation#348]
We have a CI setup on which we build our projects for android, ios and webgl. IOS builds sometimes freeze when building and never continue. Inside docker container there is many UnityShaderCompilation processes that use 0% cpu and last log from Unity says "Launched and connected shader compiler UnityShaderCompiler after 0.03 seconds".

Version: 2020.3.40f1-ios-1.0.1

**Comment by webbertakken** [comment]
Is this a bug related to GameCI? Is it related to the documentation?

Without using the proper bug report format and reporting to the relevant repository we can't really do much. It's unclear what exactly isn't working (and which component is causing it) and it's not clear what you expect the community to do about it.

I'm inclined to close this as invalid.

**Comment by webbertakken** [comment]
No trouble at all 🙂
