### ISSUE TITLE
https://game.ci/ is not accessible, error 402

### ISSUE THREAD

**Issue by mgrman-unity** [game-ci/documentation#355]
**Bug description**

https://game.ci/ is not accessible, error 402

```
This Deployment has been disabled.

Your connection is working correctly.

Vercel is working correctly.

402: PAYMENT_REQUIRED
Code: DEPLOYMENT_DISABLED
ID: fra1::k9wkw-1674729894615-6e36b01aa66b

If you are a visitor, contact the website owner or try again later.
If you are the owner, please [read this documentation section](https://vercel.com/docs/platform/fair-use-policy#typical-monthly-usage-guidelines).
```

**Steps to reproduce**

- open https://game.ci/ in browser

**Expected behavior**

- https://game.ci/ shows documentation page instead of error page

**Additional details**

![image](https://user-images.githubusercontent.com/99256329/214817075-a5373580-c24e-436b-a2d3-a035eb884cc9.png)

**Comment by webbertakken** [comment]
Thanks, Our sponsored account expired for some reason. 

I'm on it.

**Comment by sacOO7** [comment]
Please fix it 👍 . it's been down for the last 24+ hrs.

**Comment by webbertakken** [comment]
> Please fix it 👍 . it's been down for the last 24+ hrs.

I had no knowledge of it until this issue was reported 3 hours ago.

While it's down you can clone the repo and run `yarn && yarn dev` to see the docs.

**Comment by GabLeRoux** [comment]
I've contacted support as well yesterday at 20:40 montreal time, I did not have any news from Vercel yet.

We'll update here as soon as we have some feedback from Vercel support.

**Comment by GabLeRoux** [comment]
Quick status update about https://game.ci/, we have someone from Vercel support looking into this. 🤞

**Comment by sacOO7** [comment]
The site is still down : (
@webbertakken @GabLeRoux wouldn't it be better if we use [GitHub pages](https://pages.github.com/) for the time being? 
You can set gameci as a custom domain for github pages -> 
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by webbertakken** [comment]
@sacOO7 See my last comment for the temporary alternative site.

We're doing everything we can to get it back online but I'm afraid we're dependent on Vercel for this one.
