### ISSUE TITLE
Building Unity dll's in game ci

### ISSUE THREAD

**Issue by McSwan** [game-ci/documentation#359]
Hi,

I have some dll's that require the unity dll's to compile. After the dll's are compiled they put into a unity project. How do I build the dll's using game ci?

Currently I copy the dlls to github and build the dll's that way. A better way would be to use the dll's that are in game ci. But where are the dll's stored in game ci so that I can build with them ?

`name: Unity Build and Deploy
on: push

amazon-web-services
permissions:
  id-token: write
  contents: read    # This is required for actions/checkout

jobs:
    
  build:
    name: Roames World Unity DLL build
    runs-on: windows-latest # ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '3.1' ] #[ '3.0', '3.1.x', '5.0.x' ]
        

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          lfs: true
          #submodules: true
          submodules: false
          token: ${{secrets.GLOBAL_READ_REPOSITORIES_SECRET}}

      - name: Open Id env setup
        # if: contains(github.ref, 'main') || contains(github.ref, 'prd/')
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ####################################
          role-session-name: samplerolesession
          aws-region: ap-southeast-2

     # I want to use game ci dll's instead.
      - name: Copy WebGL Roames World libraries
        run: aws s3 cp s3://review-power-syd-dev.roames.com/review/Unity-2021.2.13f1/ ./Build/RoamesWorld/  --recursive

      # point environment variable to Unity's dll's
      - name: Set Environment variable for location of UnityDLLs
        run: |
          # Setting env vars is not the best 
          # https://stackoverflow.com/questions/66733076/github-actions-set-environment-variable-for-windows-build-with-powershell
          echo "UNITY_DLL_PATH=D:\a\power.modelling.roamesworld.legacycore\power.modelling.roamesworld.legacycore\Build\RoamesWorld" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "RW_DLL_PATH=" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          cd ./Build/RoamesWorld/
          dir
          dir .\..\.. 

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version

      - name: Install dependencies
        #run: dotnet restore ./Build/RoamesWorld/RoamesWorld.sln
        run: |
          cd ./Build/RoamesWorld/
          dotnet restore ./RoamesWorld.sln

      - name: Build
        run: |
          cd ./Build/RoamesWorld/
          dir env:
          dotnet build ./RoamesWorld.sln -c WebGL`

**Comment by davidmfinol** [comment]
We use Docker images to build for Unity.
Our Docker images are on Docker Hub under unityci/editor: https://hub.docker.com/r/unityci/editor

**Comment by McSwan** [comment]
I'm currently building on windows-latest.

I'm assuming I'd need to change to linux, then copy all the build files to the docker image, and build it on docker image?

Or is there someway I can set UNITY_DLL_PATH environment variable to point the docker location where the dll's are stored.

Note: I haven't used docker before.

or maybe I could copy the dll's off the game ci docker image.

` - name: Build Unity Project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
# no build - load docker image only?
          # projectPath: ./
          unityVersion: 2021.3.12f1
         
          targetPlatform: ${{ matrix.targetPlatform }}
          allowDirtyBuild: true`


Is the dokcer image availble somehow after this?

I'm thinking it's easier to just copy the dll's in like I have already done?

**Comment by davidmfinol** [comment]
If your current process is working for you, that would indeed probably be easier.

If you use the `game-ci/unity-builder@v2` action, you wouldn't have access to the docker image outside of the `game-ci/unity-builder@v2` step, so subsequent steps wouldn't be able to get the .dlls you're looking for.

I think you'd have to run the entire job in a container: https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container
I have an example of this in my `lint` job: https://github.com/finol-digital/Card-Game-Simulator/blob/fe3e2ac62fcb8b9008d46b3b218b2bf607942b0f/.github/workflows/main.yml#L82

**Comment by McSwan** [comment]
I think I'll copy the dll's in when Unity changes. A lot easier to do and fairly rare to need to do it. Nice lint script though. Thanks for your help!
