### ISSUE TITLE
Add the need for custom .gitignore extensions to the Getting Started guide.

### ISSUE THREAD

**Issue by kemmel-dev** [game-ci/documentation#365]
**Context**

I just ran into an issue where I got a 'dirty branch'.
The trouble shooting page for dirty branch tells you to clone the project into an empty folder, create a build, and see if any changes were made to autogenerated files in your project. 
This was not the case for me, however, I was still getting the issue.

![image](https://user-images.githubusercontent.com/8700780/221365499-91b2d6a1-647d-4070-88f3-affd0f0be4a4.png)

I then added
```
# Ignore results from game-ci
/[Aa]rtifacts/
/[Cc]odeCoverage/
``` 
to my .gitignore, and now no longer encounter this error.

The only mention of `.gitignore` in the docs is [here](https://game.ci/docs/getting-started/#preparing-the-project), which links to the proper Unity `.gitignore` file, but that does not include these two folders that were generated by running the workflow that follows the simple Example workflow listed [here](https://game.ci/docs/github/getting-started#simple-example).

**Suggested solution**

Add a section to the Getting Started section that explains you have to expand the default .gitignore file to get things working.

**Considered alternatives**

-

**Additional details**

-

**Comment by kemmel-dev** [comment]
I forked the documentation repo and committed my suggested improvement:

https://github.com/game-ci/documentation/compare/main...kemmel-dev:documentation:main

**Comment by webbertakken** [comment]
Great suggestion and nice work on getting started on it as well!

Feel free to open a Pull Request to `game-ci/documentation` at its `main` branch.

Note that we try to keep our documentation as concise as possible (so that people actually read it). Two points of feedback:
- My suggestion would be to reduce the amount of words needed for adding that suggestion. 
- We refer to our community as `GameCI` (functional), and only use `game-ci` when it's a namespace or implementation specific.

**Comment by kemmel-dev** [comment]
Okay, I will try to incorporate those points of feedback and submit a PR in a bit!

**Comment by davidmfinol** [comment]
Fixed by https://github.com/game-ci/documentation/pull/366

**Comment by stariluz** [comment]
I encountered the same error, but with a different file that I had excluded from the `.gitignore`:  

```sh  
...  
Warning: Changes were made to the following files and folders:  

Warning:  M Packages/manifest.json  

Error: Branch is dirty. Refusing to base semantic version on uncommitted changes  
```  

Here is my `.gitignore`:  

```sh  
...  
# The packages folder can be ignored because of Package Restore  
**/[Pp]ackages/*  
# Except for the manifest, which tells Unity which packages to install  
!**/[Pp]ackages/manifest.json  
...  
```  

Maybe I shouldn't have excluded the file, but this was the only way I found to ensure my team uses the same library versions. Do you know of a better way to handle this, or is there a way to avoid the error?

**Comment by stariluz** [comment]
Sorry to bother you. I’ve solved the problem, it was related to the out-of-space issue.  I had to separate the jobs to run them in parallel, which triggered the "out of space" issue. So, I used the action you recommended in the docs to free up space, and all my builds started passing.
 
I already commented here: [https://github.com/game-ci/unity-builder/issues/554#issuecomment-2525416383](https://github.com/game-ci/unity-builder/issues/554#issuecomment-2525416383), but I believe it’s more relevant to this repository.  
 
My project is currently very small (with an almost empty scene, a few scripts, and the usual Unity packages), and it seems strange to me that using the parallel workflow and the free-up-space action is considered optional in the docs. I can’t imagine a project that could run without this configuration (at least in Unity 6, which I’m using).

**Comment by davidmfinol** [comment]
@stariluz You're right that a good number of Unity projects won't be able to test and build on the default GitHub runners without freeing up disk space. Especially when building to Android as the target platform, I suspect that even a blank Unity project would require freeing up disk space. For that reason, we do try to show the free-disk space action alongside all builds to Android in the docs.

But there also a lot of projects that won't need an action to free disk space. It is very possible to have a project small enough to run on the default GitHub runners without freeing disk space when building to non-Android target platforms. All my personal projects do fall into this small size. 

More importantly, the free-disk-space action isn't necessarily the best solution for a project that needs more disk space than available on the default GitHub runners. Many projects may prefer to instead have self-hosted runners, or to use the cloud-runner (aka Coordinator), or to pay GitHub for larger runners. All these options are valid, and we want to bring visibility to these options.
