### ISSUE TITLE
Discord page not found

### ISSUE THREAD

**Issue by kirillmorozov** [game-ci/documentation#368]
**Bug description**

GameCI website is missing https://game.ci/discord page.

**Steps to reproduce**

1. Go to https://game.ci/discord
2. Observe Page Not Found error

**Expected behavior**

Page shows data related to the GameCI discord server.

**Additional details**

Here's a screenshot as seen on my device:

<img width="1024" alt="Discord Page Not Found" src="https://user-images.githubusercontent.com/6203454/221569604-2381ee2d-32c8-4686-857a-cd892151b7d0.png">

**Comment by webbertakken** [comment]
Thank you for reporting this!

I believe this broke when we moved from Vercel to Firebase. The reason being that I had manually configured that route in Vercel. 

We have to do the same in Firebase using the [hosting rewrites](https://firebase.google.com/docs/hosting/full-config#section-rewrites), which can be committed to the documentation repo.

**Comment by davidmfinol** [comment]
Fixed by https://github.com/game-ci/documentation/pull/381
