### ISSUE TITLE
Full workflow example for AWS cloud runners is missing

### ISSUE THREAD

**Issue by kirillmorozov** [game-ci/documentation#369]
**Bug description**

A link to "Cloud Runner GitHub sourcecode for AWS Pipeline" is no longer valid.

**Steps to reproduce**

1. Go to [GitHub Actions - AWS | GameCI](https://game.ci/docs/github-cloud-runner/getting-started/aws)
2. Scroll to the bottom of the page
3. Click on [Cloud Runner GitHub sourcecode for AWS Pipeline](https://github.com/game-ci/unity-builder/blob/main/.github/workflows/cloud-runner-aws-pipeline.yml) link
4. Observe "404 - page not found" on GitHub

**Expected behavior**

A full GameCI cloud runners on AWS example workflow shows up.

**Additional details**

<img width="1024" alt="Screenshot 2023-02-27 at 16 00 26" src="https://user-images.githubusercontent.com/6203454/221583379-08aa2c8e-146e-4991-b435-cb63ee5823c6.png">

**Comment by davidmfinol** [comment]
I believe the correct link should now be https://github.com/game-ci/unity-builder/blob/main/.github/workflows/cloud-runner-pipeline.yml

@frostebite Can you confirm?

**Comment by frostebite** [comment]
I will investigate
