### ISSUE TITLE
androidExportType not really deprecated

### ISSUE THREAD

**Issue by Haelle** [game-ci/documentation#394]
When building an AndroidAppBundle the [documentation says](https://game.ci/docs/github/builder#androidexporttype) that `androidAppBundle` is deprecated but it's not, you still have to set it to `true`. If not an APK is generated.

So from the documentation I understood that I only needed to set `androidExportType: 'androidAppBundle'` but I also have to set `androidAppBundle: true`.

I don't know if it's a bug or a problem in the documentation so I didn't made a PR on the documentation.

You can have a look to this commit that introduce [androidAppBundle: true](https://github.com/Haelle/flying_hippo/commit/081452f0bbfb63598f0842afda0e637eb4ca56cd) and the [CI](https://github.com/Haelle/flying_hippo/actions/runs/5237438556) correctly generate an AAB, where [before](https://github.com/Haelle/flying_hippo/actions/runs/5237264840) it was an APK.

P.S: ok you cannot see the artifcats but I assure you it was an APK

**Comment by davidmfinol** [comment]
The documentation got a bit ahead here. This should be fixed once `v3` is released.
