### ISSUE TITLE
The versions page is a bit broken

### ISSUE THREAD

**Issue by GabLeRoux** [game-ci/documentation#410]
As mentionned here:  
https://github.com/game-ci/unity-builder/pull/559#issuecomment-1686159470

> I realise the [versions page](https://game.ci/docs/docker/versions) is a bit broken right now but you can use the dropdown to select v1.1.2.
> 
> ![image](https://user-images.githubusercontent.com/20756439/262010640-3bbb0639-6e5d-432d-986e-7f85062d4867.png)

<details>
<summary>Other screenshots</summary>

![ScreenShot Google Chrome 2023-08-21 at 15 38 44](https://github.com/game-ci/documentation/assets/1264761/f748801a-dfb2-4c6a-9d40-a2112820da7d)

![ScreenShot Google Chrome 2023-08-21 at 15 38 32](https://github.com/game-ci/documentation/assets/1264761/21e179b9-3b31-468b-90ef-81eac1bff2ad)

![ScreenShot Google Chrome 2023-08-21 at 15 38 25](https://github.com/game-ci/documentation/assets/1264761/37e2e44f-595f-4fb7-aadd-d1800d58e149)

![ScreenShot Google Chrome 2023-08-21 at 15 38 24](https://github.com/game-ci/documentation/assets/1264761/7c6e5b4c-d727-412e-9aac-20d748cbf6da)

![ScreenShot Google Chrome 2023-08-21 at 15 38 46](https://github.com/game-ci/documentation/assets/1264761/ef12c49a-3ec3-4d24-92b3-8dd1809f4c05)

</details>

**Comment by EliasVal** [comment]
Will tackle this one too ;)

**Comment by GabLeRoux** [comment]
I'm reopening this as because when we reverted the changes to home page that were not ready, we forgot about this one. I'll merge the versions page changes back right away.
