### ISSUE TITLE
Make the homepage look a bit more professional

### ISSUE THREAD

**Issue by webbertakken** [game-ci/documentation#411]
**Context**

The https://game.ci homepage is the first impression people get from GameCI.

We a thousands of projects now using GameCI, I think we could do with a bit more professional look for the homepage.

**Suggested solution**

We need more content like a section with companies that use GameCI, a bit of an introduction and ideally a nice animation that shows that GameCI can be used in any VCS system (GitHub, GitLab, others).

**Considered alternatives**

We've considered hiring someone for this kind of work but our costs are already higher than the donations we get.

**Additional details**

There are already some [planned sections](https://github.com/game-ci/documentation/blob/main/src/pages/index.tsx) and their respective [placeholder components](https://github.com/game-ci/documentation/tree/main/src/components/pages/home/section). We just need a few people to finish some of these sections.

**Comment by EliasVal** [comment]
I'll fork #407 for this :)
