### ISSUE TITLE
Unity does not support personal license for manual activation anymore.

### ISSUE THREAD

**Issue by OneBogdan01** [game-ci/documentation#413]
**Bug description**

Exactly what the title says

**Steps to reproduce**

- Go to https://license.unity3d.com/manual and provide a .alf file
- Afterwards you are prompted with the serial number instead of letting you choose which kind of license you want.

I have tried searching for a version of that unity site that still worked.

**Expected behavior**

Normally you could just click next and select personal unity license and get your .ulf file.

**Additional details**
![image](https://github.com/game-ci/documentation/assets/31468440/96025f74-f442-4de8-82e0-4861dea59cac)

**Comment by webbertakken** [comment]
duplicate of #408
