### ISSUE TITLE
Add a search feature powered by algolia

### ISSUE THREAD

**Issue by GabLeRoux** [game-ci/documentation#45]
**Is your feature request related to a problem? Please describe.**
Right now, we cannot search through all documentation.

**Describe the solution you'd like**
 We should be able to search for things like `activation`, `android` or `IL2CPP` and clicking on the result, we should navigate to the related documentation section. An example of this is on [Fastlane's documentation website](https://docs.fastlane.tools/).

![image](https://user-images.githubusercontent.com/1264761/95375362-8180d300-08ad-11eb-9089-5da732f8f0e0.png)

**Additional context**
* The search bar should be placed at the top of the website using antd's provided components

**Comment by zachesposito** [comment]
Hello I would like to take care of this issue

**Comment by webbertakken** [comment]
Great @zachesposito,

Please go ahead and let us know if you need any additional info or help. 

We're also on [discord](https://unity-ci.com/discord) if you like to discuss things more quickly.

**Comment by webbertakken** [comment]
Removing assignment as there is no fork. Feel free to assign yourself when you start

**Comment by davidmfinol** [comment]
@webbertakken https://github.com/game-ci/documentation/issues/97 is still open, but I think we can close this since you've done the initial implementation, right?

**Comment by webbertakken** [comment]
Yea agreed.
