### ISSUE TITLE
Wrong code in "Multiple private Github repositories" documentation

### ISSUE THREAD

**Issue by brianzaubar** [game-ci/documentation#481]
In the first action step "uses: webfactory/ssh-agent@v0.8.0" [here](https://game.ci/docs/github/builder/#multiple-private-github-repositories) you forgot to indent the "ssh-private-key" property underneath the "with" I believe.

**Comment by webbertakken** [comment]
Yep, that's a bug. Thank you for reporting it!

Happy to take the correction in a PR.
