### ISSUE TITLE
More detailed Android build & sign

### ISSUE THREAD

**Issue by louis030195** [game-ci/documentation#69]
**Is your feature request related to a problem? Please describe.**

Lack of details on Android pipeline.

**Describe the solution you'd like**

Either detailed CLI in the documentation to create a keystore etc. either a standalone page "Android tutorial" with screenshots, "click here on IDE ..."

**Describe alternatives you've considered**

Google

**Additional context**

I did a mistake when trying to create the keystore, first followed the Google search Android stuff but actually it's just simple to create a keystore through Unity UI, might win some time to the reader.
(Now my build works btw)

**Comment by webbertakken** [comment]
Thank you @louis030195 for your feature request!

We're accepting contributions from the community for this.

**Comment by webbertakken** [comment]
We now have documentation on Android and iOS for both github actions and gitlab workflow.

Feel free to reopen or create another issue if you're still missing things.
