### ISSUE TITLE
Document Image Tag pattern

### ISSUE THREAD

**Issue by dominicmarmionswrve** [game-ci/documentation#91]
Hi, 

Could you document the tag pattern for the images? I'm migrating from gableroux (🏆 ) images which had the pattern documented [here](https://gitlab.com/gableroux/unity3d#how-and-where-do-i-find-the-right-docker-image).

Right now, if I search for `2019.4.14f1-android` in docker [here](https://hub.docker.com/r/unityci/editor/tags?page=1&ordering=last_updated&name=2019.4.14f1-android), it returns several and its not clear which one to use.

Thanks!

**Comment by webbertakken** [comment]
Good idea.

In the meantime: 

`[base platform]-[unity editor version]-[target-platform]-[our docker repository version]`

Example:

`ubuntu-2019.3.14f1-android-0.9.0`

Not that if you're using unity actions, you don't need to know the image tag structure, as all you need to know are parameters that you pass into the action.

**Comment by dominicmarmionswrve** [comment]
Thank you!

We've recently migrated from jenkins to circleci and only just got to grips with things when we realised the gableroux images were deprecated. Not sure if unity actions is a fit for us, but I'll take a look.
