### ISSUE TITLE
Update github docs v2 to reflect changes in unity actions since v2 alpha

### ISSUE THREAD

**Issue by webbertakken** [game-ci/documentation#94]
**Is your feature request related to a problem? Please describe.**
We have recently introduced versioning into the docs. Unity actions on GitHub now have v1 and v2. 
- v1 should no longer be changed
- v2 should be updated to show latest behaviour with the new images and use repo version v2.0-alpha or higher.

**Comment by davidmfinol** [comment]
I raised https://github.com/game-ci/documentation/pull/99 with the assumption users will be able to use a simple `v2` as the version.

**Comment by webbertakken** [comment]
I have tried that, but this in fact does not work as far as I know. I remember trying it and failing it. (this may have been due to the `-alpha` suffix though).

**Comment by webbertakken** [comment]
Closing this as #99 is merged.
